# Generated by Django 5.1.3 on 2024-12-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(help_text='Type of work performed (e.g., Maintenance, Repair, etc.)', max_length=150)),
                ('members_count', models.BigIntegerField(help_text='Number of members involved')),
                ('floor_number', models.CharField(help_text='Floor number or description of the location', max_length=50)),
                ('equipments_used', models.TextField(help_text='List of equipments used, separated by spaces')),
                ('photos', models.ImageField(blank=True, help_text='Comma-separated list of photo paths', null=True, upload_to='reports/photos/')),
                ('report_details', models.TextField(help_text='Write report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app1.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
