# Generated by Django 5.1.3 on 2024-12-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='equipments_used',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='floor_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='members_count',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='reports/photos/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='work_type',
            field=models.CharField(max_length=150),
        ),
    ]
