# Generated by Django 5.1.3 on 2024-12-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_report_equipments_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
