# Generated by Django 5.1.3 on 2024-12-06 20:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_report_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='reports-photos'),
        ),
    ]
